is_prod: false

db:
  dsn: host=pal_db port=5432 user=postgres dbname=newpal password=postgres TimeZone=UTC
  type: postgres

redis:
  addr: pal_redis:6379
  pass: ""
  db: 0

auth:
  access_secret_key: zxliLHUIh908hOUh
  access_lifetime_minutes: 20
  refresh_lifetime_hours: 48
  signing_method: HS512
  auth_head_name: Bearer
  table_prefix: jwt12345_

cors:
  white_list:
    - "http://localhost:4300"
  allow_all: false
