version: '3'

services:
  pal_db:
    image: postgis/postgis
    hostname: pal_db
    env_file:
      - pgsql-vars.env
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - newpal-network

  pal_adminer:
    image: adminer
    hostname: pal_adminer
    ports:
      - "8080:8080"
    networks:
      - newpal-network

#  rabbitmq:
#    image: rabbitmq:latest
#    hostname: pal_rabbitmq
#    env_file:
#      - rmq/rmq_variables.env
#    ports:
#      - "15673:15672"
#      - "5673:5672"
#    volumes:
#      - ./rmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
#    networks:
#      - newpal-network

  pal_redis:
    image: redis
    hostname: pal_redis
    ports:
      - "6380:6379"
    networks:
      - newpal-network

  pal_web:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    hostname: pal_web
    environment:
      - NEWPAL_ENV=dev
    volumes:
      - ..:/usr/src/app
    ports:
      - "9099:8000"
    depends_on:
      - pal_db
#      - rabbitmq
    networks:
      - newpal-network


networks:
  newpal-network:
